# Generated by Django 5.1.2 on 2024-11-02 15:09

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Phone')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('recruiter', 'recruiter'), ('administrator', 'Administrator')], default='recruiter', max_length=50)),
                ('avatar', image_cropping.fields.ImageCropField(blank=True, default='default_avatar.png', null=True, upload_to='avatars', verbose_name='Avatar')),
                ('cropping', image_cropping.fields.ImageRatioField('avatar', '430x430', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
        ),
    ]
