# Generated by Django 5.1.2 on 2024-11-02 16:02

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=image_cropping.fields.ImageCropField(blank=True, default='D:\\Python\\Projects\\MSFT_Recruitment\\msft_recruitment\\userIcon.png', null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
