# Generated by Django 5.1.2 on 2024-11-02 18:19

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_member_avatar_alter_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=image_cropping.fields.ImageCropField(blank=True, default='D:\\Python\\Projects\\MSFT_Recruitment\\MSFT-Recruitment\\msft_recruitment\\userIcon.png', null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
